"""
Django settings for ptt_sounds project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']
# SECURITY WARNING: keep the secret key used in production secret!
SCRAPINGHUB_APIKEY = os.environ['SCRAPINGHUB_APIKEY']
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ['DEBUG'] == 'True' # environment vars are strings. "convert" to boolean.

ALLOWED_HOSTS = [
    os.environ['ALLOWED_HOSTS_1']
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_results',
    'rest_framework', # Django RESTful Framework
    'corsheaders', # allowing Cross-Origin Resource Sharing (CORS), whitelist is set below
    'backend_app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# update root project directory for urlconf and wsgi app
ROOT_URLCONF = 'ptt_sounds.urls'
WSGI_APPLICATION = 'ptt_sounds.wsgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': os.environ['DB_HOST'],
        'PORT': os.environ['DB_PORT'],
        'NAME': os.environ['DB_NAME'],
        'USER': os.environ['DB_USER']
    }
}
# if DB_PASS is specified
if 'DB_PASS' in os.environ:
    DATABASES['default']['PASSWORD'] = os.environ['DB_PASS']

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
STATIC_URL = os.environ['STATIC_HOST']+os.environ['STATIC_URL']

# collectstatic directory (located OUTSIDE the base directory)
STATIC_ROOT = os.environ['STATIC_ROOT']
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
# setup wave media root (we avoid using MEDIA_ROOT because it does not serve user uploaded contents)
WAV_MEDIA_ROOT = os.environ['WAV_MEDIA_ROOT']
WAV_MEDIA_URL = os.environ['WAV_MEDIA_HOST']+os.environ['WAV_MEDIA_URL']

# Add for RESTful Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES' : [
        # provide read-only acess for anonymous users
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}

# Only use in dev env
# CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = (
    os.environ['CORS_WL_1']
)

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True

# use redis as cache backend instead of db
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ['CACHES_LOCATION'],
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# use redis as session engine
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# for celery
CELERY_BROKER_URL = os.environ['CELERY_BROKER_URL']
CELERY_BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600}
# use django's db as result backend instead of 'redis://localhost:6379/'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERYD_MAX_TASKS_PER_CHILD = 1
CELERY_ALWAYS_EAGER = False
